# Generated by Django 5.1.1 on 2024-09-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_comment_tutorial_id_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tutorial_id',
        ),
    ]
