# Generated by Django 5.1.1 on 2024-09-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_comment_tutorial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tutorial_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.tutorial'),
        ),
    ]
