# Generated by Django 5.1.1 on 2024-10-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_comment_tutorial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tutorial_id',
        ),
    ]
